### PR TITLE
File handler refactor

### PR DESCRIPTION
**Pull request by bmschmidt**
OK, this refactor is ready for discussion. Would love it if @organisciak tried running it for a bit, and at some point we can see if it runs to master. Still buggy, but I think this might be in good enough shape to work on other machines. I will write some tests once I get parquet writing and caching fully set up, but I think they'll basically look like a loop rountripping some files through a variety of formats and storage engines.

This aims to solve #17 #12 #8 #10.

It opens the way for elaborate configuration files without implementing them yet.

A couple notes:

## Code splits. 

`FileHandler` objects live in `parsers.py`, `IdResolver` objects live in `id_resolvers.py`.

## Compatibility

In most cases (unnamed paths to json; named ids to http) this should work the same 
as the existing module. But there may be edge cases I'm unaware, for example involving the Volume object's `id` element. I've looked much less at the FeatureReader class than Volume, and that likely needs a few changes. 

## Storage backends.

This uses storage backends that are accessed by calling `open` from a handler object.

```python
handler = PairtreeResolver(dir = "/hathi-features", format = "json", compresison = "bz2")
with handle.open("hvd.1234566", mode = "wb") as vol:
    vol.read().decode("utf-8")
```

## Defaults

A lot of the big questions here are around defaults and the use of kwargs.

In general, I often use a strategy of initializing with **kwargs and a couple required fields
and then populating like this that allows a class-level default.

```python
compression = kwargs.get("compression", self.compression).
```

Since the new functions will not generally be called by normal users, I've mostly tried to avoid supplying default arguments; but then this kwargs fallback ends up doing it.

One of the big things here is that it allows a user to explicitly pass `compression = None`
without **requiring** a compression arg.

But I've teased out a few bugs where I wasn't rigorous about this approach, and it may introduce some subtle bugs.

### CODE REVIEW

**Comment by bmschmidt** [comment]
Oh, and see [this notebook](https://github.com/massivetexts/htrc-feature-reader/blob/FileHandlerRefactor/examples/Accessing%20volumes%20by%20ids.ipynb) for a discussion of accessing by IDs.

**Comment by organisciak** [comment]
Working through this today.

**Comment by bmschmidt** [comment]
Cool. There are still plenty of bugs, and I'll write the tests to shake them out. But for now, the big Qs I see are about organization philosophy, argument names, defaults, and philosophy around the use of **kwargs and defaults from it.

**Comment by organisciak** [comment]
Nearly passing all tests, except any parquet reading. I'll have to return to that another day.

**Comment by bmschmidt** [comment]
OK, I've made another stab through this. This breaks some of the tests again, sorry, but re-enables the things in the illustrative ipython notebook that I will move in as tests.

It also moves towards a more uniform treatment of 'ids' in the FeatureReader class; currently there's a lot of swapping between 'id' and 'path' methods, but to the parsers a 'path' is just an 'id' resolved using PathResolver. So I'm settling that earlier.

**Comment by bmschmidt** [comment]
BTW, something to watch out for--there's a minefield of problems for default values to 'compression.' Since None is a valid type of compression, it's not safe to use it as a placeholder for 'no passed argument.' and the default compression varies by format and file origin.  so instead I've removed it as a named parameter in general, and defaults arise when compression isn't in the kwargs bundle. 

---

Editing this comment to say: I've just added 'default' keys to compression to facilitate making choices when necessary. Works much better.

**Comment by bmschmidt** [comment]
OK, I've made a number of changes to this. I believe that most of the failing tests now relate to questions about how we expect parquet parsing to be named.

I've started adding some more interesting code and tests involving moving data among different resolvers. This will facilitate caching and fallback strategies soon.

More tests are still needed. I'm planning to write one that just goes through all permutations of 'format', 'compression', and 'id_resolver' and sees if it can read or write (or raise a NotImplementedError).

I always have trouble writing true unit tests as opposed to integration tests, but the latter will at least give us coverage.

**Comment by bmschmidt** [comment]
This branch now includes the updated chunking discussed in #9 with a few more for some unexpected edge cases that came up in testing but not in 50K random volumes.

I've mostly removed the failing parquet tests.

It adds travis testing to all versions from 3.5 and up addressing a question remaining in #16.

**Comment by organisciak** [comment]
Thanks for updating the tests. I'll update all the project code separately since I'm the only one using parquet.

I'll polish the remaining tests and merge this into master to close the ticket. Currently trying to figure out why giving parquet file and specifying 'json' format works.

**Comment by organisciak** [comment]
We're live, yay!!!

To be clear, `compression=None` refers to a lack of compression here. No need in Python to do `arg='default'` in an `_init_` method if there's no extra logic, just do `arg=` for whatever the default is.  for that named argument.

**Comment by bmschmidt** [comment]
Great! I'm teaching for a couple days, but will try to mop up remaining issues soon.

**Pull request merged**
